# Generated by Django 5.0.2 on 2025-07-11 20:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_label_board_alter_board_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boardmembership',
            unique_together={('board', 'user')},
        ),
    ]
